apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
  namespace: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - image: shadialtadouka/mynginx:latest
        name: httpd
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 400Mi
          limits:
            cpu: 200m
            memory: 800Mi